import base64

import yaml

from mergebot.tools.gitlab.api_wrapper import GitlabAPIWrapper


class InvalidMergebotYAML(Exception):
    """Raised when .mergebot.yml exists but is not valid YAML."""


class GitlabOnboardingManager:
    """
    Handles GitLab onboarding operations for Mergebot, such as managing the .mergebot.yml
    configuration file, checking if onboarding pull requests (merge requests) exist,
    creating onboarding merge requests, and validating YAML configuration files.

    Provides utility methods to interact with the GitLab repository using the API wrapper,
    enabling streamlined onboarding workflows for repositories integrating with Mergebot.
    """

    def __init__(self):
        self._api_wrapper = None

    @property
    def api_wrapper(self):
        """Lazy initialization of API wrapper to ensure project is available."""
        if self._api_wrapper is None:
            self._api_wrapper = GitlabAPIWrapper()
        return self._api_wrapper

    @property
    def project(self):
        return self.api_wrapper.gitlab_repo_instance

    def get_mergebot_yml(self):
        """
        Retrieves and parses the .mergebot.yml file from the default branch.

        Returns:
            dict: Parsed YAML content if the file exists and is valid.
            None: If the file does not exist.

        Raises:
            InvalidMergebotYAML: If the file exists but contains invalid YAML.
        """
        try:
            file = self.project.files.get(
                file_path=".mergebot.yml", ref=self.project.default_branch
            )
            content = base64.b64decode(file.content).decode()
            return yaml.safe_load(content)
        except yaml.YAMLError as e:
            raise InvalidMergebotYAML(f"Invalid YAML in .mergebot.yml: {e}")
        except Exception:
            return None

    def onboarding_pr_exists(self, branch_name: str = "mergebot/onboarding"):
        """
        Checks if an onboarding PR from branch_name to the default branch already exists.
        Returns the PR web_url if found, else None.
        """
        default_branch = self.project.default_branch
        mrs = self.project.mergerequests.list(
            source_branch=branch_name,
            target_branch=default_branch,
            state="opened",
            all=True,
        )
        return mrs[0].web_url if mrs else None

    def create_onboarding_pr(
        self, default_content: str, branch_name: str = "mergebot/onboarding"
    ):
        """
        Creates an onboarding PR to add .mergebot.yml to the default branch.
        """
        default_branch = self.project.default_branch

        # Ensure the branch exists (create if not)
        if not self._branch_exists(branch_name):
            self.project.branches.create({"branch": branch_name, "ref": default_branch})

        # Write or update the file in the onboarding branch
        self.api_wrapper.update_file(
            branch_name=branch_name,
            file_path=".mergebot.yml",
            file_contents=default_content,
            commit_message="chore: add .mergebot.yml for onboarding",
        )

        description = (
            "### Mergebot Onboarding PR\n\n"
            "This PR was generated automatically by **Mergebot** to help you get started with repository-based configuration.\n\n"
            "- A default `.mergebot.yml` file has been added to your repository.\n"
            "- Please review and customize this file to fit your team's workflow and requirements.\n"
            "- For details on configuration options and best practices, see the [Mergebot Onboarding Guide](https://github.com/thehapyone/mergebot/blob/main/README.md).\n\n"
            "**Why am I seeing this PR?**\n"
            "- Mergebot requires a `.mergebot.yml` file in your default branch to operate.\n"
            "- This PR ensures your repository is ready for automated code review and merge automation.\n\n"
            "If you have questions or need help, please refer to the documentation or open an issue.\n\n"
            "_Generated by [Mergebot](https://github.com/thehapyone/mergebot)_"
        )

        mr = self.project.mergerequests.create(
            {
                "source_branch": branch_name,
                "target_branch": default_branch,
                "title": "Add .mergebot.yml",
                "remove_source_branch": True,
                "description": description,
            }
        )
        return mr.web_url

    def _branch_exists(self, branch_name: str) -> bool:
        """Check if a branch exists in the project."""
        try:
            self.project.branches.get(branch_name)
            return True
        except Exception:
            return False
