repos:
  - repo: local
    hooks:
      - id: format
        name: Format code
        entry: make format
        language: system
        pass_filenames: false

      - id: lint
        name: Lint code
        entry: make lint
        language: system
        pass_filenames: false

      - id: spell-check
        name: Spell check
        entry: make spell_check
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
