[project]
name = "mergebot"
version = "0.1.0"
description = "A bot for analysis, approving, and merging pull/merge requests"
authors = [
    {name = "Ayo Ayibiowu",email = "charlesayibiowu@hotmail.com"}
]
license = {text = "Apache License 2.0"}
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "crewai (==0.140)",
    "crewai-tools (==0.49.0)",
    "python-gitlab (>=5.6.0,<6.0.0)"
]


[project.scripts]
mergebot = "mergebot.app:cli_entry"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = true

[tool.poetry.group.dev.dependencies]
codespell = "^2.4.1"
ruff = "^0.12.2"

[tool.codespell]
ignore-words-list = "allEdges,astroid"
skip = "poetry.lock"
