[project]
name = "mergebot"
version = "0.1.0"
description = "A bot for analysis, approving, and merging pull/merge requests"
authors = [
    {name = "Ayo Ayibiowu",email = "charlesayibiowu@hotmail.com"}
]
license = {text = "Apache License 2.0"}
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "crewai (>=0.102.0,<0.103.0)",
    "crewai-tools (>=0.36.0,<0.37.0)",
    "python-gitlab (>=5.6.0,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
codespell = "^2.4.1"
ruff = "^0.9.9"

