from typing import Any

from mergebot.project_registry import ProjectRuntime
from mergebot.services import approval_service, merge_service
from mergebot.services.scoring import AUTO_APPROVE, render_recommendation
from mergebot.tools.github.api_wrapper import GitHubAPIWrapper
from mergebot.tools.gitlab.api_wrapper import GitlabAPIWrapper
from mergebot.validator.logging_config import logger


def _is_conclusive_impact_assessment(data: dict) -> bool:
    """
    An assessment is conclusive only if BOTH recommendation and score were extracted.
    - recommendation: non-empty after trimming
    - score: non-empty and not in {"N/A","NA"} (case-insensitive)
    """
    if not isinstance(data, dict):
        return False
    rec = str(data.get("recommendation", "") or "").strip()
    score = str(data.get("score", "") or "").strip()
    if not rec or not score:
        return False
    return score.upper() not in {"N/A", "NA"}


def _build_messages(platform_type: str) -> dict[str, str]:
    pr_style = "MR" if platform_type == "gitlab" else "PR"
    return {
        "approval": (
            f"✅ {pr_style} has been auto-approved as recommended in the Impact Assessment Report (see assessment report).\n"
            "This action has been automated as per the established policy.\n"
            "If CI or downstream issues arise, please review the report or raise an issue manually."
        ),
        "not_approved": (
            f"❌ {pr_style} has not been auto-approved as per the Impact Assessment Report.\n"
            "Please review the report and take necessary actions manually."
        ),
        "inconclusive": (
            "⚠️ Impact Assessment result appears inconclusive or not in the expected format.\n\n"
            "Recommended next steps:\n"
            "- Consider using a more capable AI model for the Impact Evaluator crew.\n"
            "- Review your approval configuration (docs/configuration/approval_policy.md).\n"
            "- Review the Mergebot logs for potential errors or truncation.\n\n"
            "This review will be held for human attention. No auto-approval has been performed."
        ),
    }


async def post_merge_failed_reason(
    pr_id, score_val, merge_threshold, reasons, runtime: ProjectRuntime
):
    reasons_text = ", ".join(reasons) if reasons else "Unknown reason"
    msg = (
        "⚠️ Merge skipped\n"
        f"- Reason(s): {reasons_text}\n"
        f"- Weighted score: {score_val if score_val else 'Unavailable'} (merge threshold: {merge_threshold if merge_threshold else 'Unavailable'})\n"
    )
    await approval_service.post_comment(pr_id, msg, runtime)


def generate_final_decision(impact_assessment, approved_flag, action_note, analysis_link):
    # The recommendation crosses this boundary as the scoring enum; the dashboard
    # row is a render surface, so it gets the human-readable phrasing.
    recommendation = str(impact_assessment.get("recommendation", "") or "")
    final_decision = {
        "recommendation": render_recommendation(recommendation),
        "impact_score": impact_assessment.get("score"),
        "action_taken": action_note,
        "analysis_link": analysis_link,
        "approved": approved_flag,
    }

    return final_decision


def _get_bot_identity(runtime: ProjectRuntime) -> str:
    """
    Best-effort retrieval of the Mergebot service account identity for instructions.
    """
    try:
        platform = runtime.platform_type
        if platform == "github":
            wrapper = GitHubAPIWrapper(config=runtime.config, project_path=runtime.project_path)
        elif platform == "gitlab":
            wrapper = GitlabAPIWrapper(config=runtime.config, project_path=runtime.project_path)
        else:
            return ""
        identity = wrapper.get_bot_identity()
        return identity or ""
    except Exception as exc:  # pragma: no cover - defensive fallback
        logger.debug("Failed to resolve bot identity: %s", exc)
        return ""


def _build_retrigger_section(runtime: ProjectRuntime) -> str:
    bot_identity = _get_bot_identity(runtime)
    mention = f"@{bot_identity}" if bot_identity else "@mergebot"
    pr_label = "MR" if runtime.platform_type == "gitlab" else "PR"
    return (
        "<details>\n"
        "<summary>Requesting Another Review</summary>\n\n"
        "| Trigger | Command | Description |\n"
        "| --- | --- | --- |\n"
        "| Comment command | `/mergebot review` | Queue an immediate re-analysis by Mergebot. |\n"
        f"| Mention | `{mention}` | Mention the Mergebot account in any {pr_label} comment to request a follow-up review. |\n"
        f'| Dashboard | Check "Request a Rerun" in the Mergebot dashboard | Adds this {pr_label} to the rerun queue for the next scheduled scan. |\n\n'
        "</details>\n\n"
        "> _This report was automatically generated by [MergeBot](https://github.com/thehapyone/Mergebot)"
        "```"
    )


def _ensure_retrigger_guidance(report: str, runtime: ProjectRuntime) -> str:
    """
    Append re-trigger instructions to the impact assessment report if not already present.
    """
    if not report:
        return report
    if "Requesting Another Review" in report:
        return report
    section = _build_retrigger_section(runtime)
    if not section:
        return report
    body = report.rstrip()
    if body.endswith("```"):
        body = body[:-3]
    separator = "\n\n---\n\n" if body else ""
    return f"{body}{separator}{section}\n"


async def _handle_inconclusive_decision(
    pr_id: int,
    impact_assessment: dict[str, Any],
    messages: dict[str, str],
    runtime: ProjectRuntime,
) -> dict[str, Any]:
    analysis_link = await approval_service.post_comment(pr_id, messages["inconclusive"], runtime)
    action_note = "Human review required (inconclusive)"
    final_decision = generate_final_decision(
        impact_assessment,
        approved_flag=False,
        action_note=action_note,
        analysis_link=analysis_link,
    )
    final_decision["recommendation"] = action_note
    return final_decision


async def _process_rejection(
    pr_id: int, messages: dict[str, str], runtime: ProjectRuntime
) -> tuple[bool, str]:
    try:
        await approval_service.post_comment(pr_id, messages["not_approved"], runtime)
        return False, "Not approved"
    except Exception as e:  # pragma: no cover - defensive logging path
        logger.error(f"Failed to post 'not approved' comment: {e}")
        return False, f"Failed to post comment: {e}"


async def _process_approval(
    pr_id: int,
    impact_assessment: dict[str, Any],
    messages: dict[str, str],
    runtime: ProjectRuntime,
    analysis_link: str,
) -> tuple[bool, str, str]:
    approved_flag = False
    action_note = ""

    try:
        await approval_service.approve_change(pr_id, runtime)
        await approval_service.post_comment(pr_id, messages["approval"], runtime)
        action_note = "Approved"
        approved_flag = True
    except Exception as e:
        logger.error(f"Approval action failed: {e}")
        action_note = f"Approval failed: {e}"
        await approval_service.post_comment(pr_id, f"⚠️ Approval failed: {e}", runtime)
        return approved_flag, action_note, analysis_link

    merge_cfg = getattr(runtime.config, "merge", None)
    if not merge_cfg or not merge_cfg.enabled:
        await approval_service.post_comment(
            pr_id,
            "Auto-merge is disabled by configuration. PR approved.",
            runtime,
        )
        return approved_flag, action_note, analysis_link

    raw_score = impact_assessment.get("score")
    score_val = merge_service.parse_first_float(raw_score)
    approval_threshold = (
        runtime.config.approval_policy.threshold if runtime.config.approval_policy else None
    )
    merge_threshold = merge_cfg.threshold if merge_cfg.threshold is not None else approval_threshold

    score_ok_for_merge = (
        approved_flag
        and (score_val is not None)
        and (merge_threshold is not None)
        and (score_val <= merge_threshold)
    )

    if not score_ok_for_merge:
        reasons = [
            (
                "Impact score above merge threshold"
                if score_val is not None
                else "Impact score unavailable"
            )
        ]
        await post_merge_failed_reason(pr_id, score_val, merge_threshold, reasons, runtime)
        return approved_flag, action_note, analysis_link

    status = await merge_service.get_status(pr_id, runtime)
    rules_dict = (
        merge_cfg.rules.model_dump()
        if hasattr(merge_cfg.rules, "model_dump")
        else dict(merge_cfg.rules)
    )
    allowed_by_rules, reasons = merge_service.evaluate_rules(
        status, rules=rules_dict, enforce_never_merge_draft=True
    )

    prefixes = getattr(getattr(merge_cfg, "rules", None), "branch_prefixes", None)
    if prefixes:
        source_branch = (status.get("source_branch") or "").strip()
        if not any(isinstance(p, str) and source_branch.startswith(p) for p in prefixes):
            allowed_by_rules = False
            reasons.append(f"Source branch '{source_branch or '?'}' not allowed by prefix rules")

    if not allowed_by_rules:
        await post_merge_failed_reason(pr_id, score_val, merge_threshold, reasons, runtime)
        return approved_flag, action_note, analysis_link

    try:
        result = await merge_service.merge_change(pr_id, runtime, strategy=merge_cfg.strategy)
        summary = (
            f"✅ Auto-merged using strategy: {merge_cfg.strategy}\n"
            f"- Weighted score: {score_val} (threshold: {merge_threshold})\n"
            f"- CI: {status.get('ci_passed')}, "
            f"Reviews: approved={status.get('reviews', {}).get('approved')}, "
            f"changes_requested={status.get('reviews', {}).get('changes_requested')}, "
            f"Mergeable: {status.get('mergeable')}, "
            f"Approval state: {status.get('approval_state')}\n"
            f"- Result: {result}"
        )
        await approval_service.post_comment(pr_id, summary, runtime)
        action_note = "Approved and merged"
    except Exception as e:  # pragma: no cover - external API failure path
        logger.error(f"Merge action failed: {e}")
        await approval_service.post_comment(pr_id, f"⚠️ Merge failed: {e}", runtime)

    return approved_flag, action_note, analysis_link


async def process_decision(
    pr_id: int, impact_assessment: dict[str, Any], runtime: ProjectRuntime
) -> dict[str, Any]:
    """
    Orchestrates posting the assessment, approving if applicable, and auto-merging under guardrails.

    Returns:
      final_decision: dict with recommendation, impact_score, action_taken, analysis_link, approved
      analysis_link: permalink to the posted analysis/comment
      approved_flag: bool indicating whether approval was performed
    """
    messages = _build_messages(runtime.platform_type)
    rec = str(impact_assessment.get("recommendation", "") or "").strip()
    report = str(impact_assessment.get("report", "") or "")

    if not _is_conclusive_impact_assessment(impact_assessment):
        return await _handle_inconclusive_decision(pr_id, impact_assessment, messages, runtime)

    enriched_report = _ensure_retrigger_guidance(report, runtime)
    analysis_link = await approval_service.post_comment(pr_id, enriched_report, runtime)

    # Exact match on the scoring enum — never a substring check, which once
    # normalized phrasings like "Do not approve" into an approval.
    if rec == AUTO_APPROVE:
        approved_flag, action_note, analysis_link = await _process_approval(
            pr_id, impact_assessment, messages, runtime, analysis_link
        )
    else:
        approved_flag, action_note = await _process_rejection(pr_id, messages, runtime)

    return generate_final_decision(impact_assessment, approved_flag, action_note, analysis_link)
