import base64
from abc import ABC, abstractmethod

import yaml


class InvalidMergebotYAML(Exception):
    """Raised when .mergebot.yml exists but is not valid YAML."""


class OnboardingManagerBase(ABC):
    """
    Abstract base class for unified onboarding managers.
    """

    def __init__(self):
        self._api_wrapper = None
        self.vcs = None
        self.config_file = ".mergebot.yml"
        self.pr_title = "chore: configure .mergebot.yml"
        self.onboarding_branch = "mergebot/onboarding"

    @staticmethod
    def pr_description() -> str:
        """
        Shared onboarding PR description.
        """
        return (
            "### Mergebot Onboarding PR\n\n"
            "This PR was generated automatically by **Mergebot** to help you get started with repository-based configuration.\n\n"
            "- A default `.mergebot.yml` file has been added to your repository.\n"
            "- Please review and customize this file to fit your team's workflow and requirements.\n"
            "- For details on configuration options and best practices, see the [Mergebot Onboarding Guide](https://github.com/thehapyone/mergebot/blob/main/README.md).\n\n"
            "**Why am I seeing this PR?**\n"
            "- Mergebot requires a `.mergebot.yml` file in your default branch to operate.\n"
            "- This PR ensures your repository is ready for automated code review and merge automation.\n\n"
            "If you have questions or need help, please refer to the documentation or open an issue.\n\n"
            "_Generated by [Mergebot](https://github.com/thehapyone/mergebot)_"
        )

    @property
    def project(self):
        if self.vcs == "github":
            return self.api_wrapper.github_repo_instance
        elif self.vcs == "gitlab":
            return self.api_wrapper.gitlab_repo_instance
        raise NotImplementedError(
            "Project property must be implemented in subclasses for specific VCS."
        )

    def get_file_contents(self):
        """
        Retrieves the contents of a file from the repository.
        """
        if self.vcs == "github":
            return self.project.get_contents(
                self.config_file, ref=self.project.default_branch
            )
        elif self.vcs == "gitlab":
            return self.project.files.get(
                file_path=self.config_file, ref=self.project.default_branch
            )
        raise ValueError("Unsupported VCS type for file retrieval.")

    def branch_exists(self) -> bool:
        """
        Checks if a branch exists in the project.
        """
        try:
            if self.vcs == "github":
                self.project.get_branch(self.onboarding_branch)
            elif self.vcs == "gitlab":
                self.project.branches.get(self.onboarding_branch)
            else:
                raise ValueError("Unsupported VCS type for branch existence check.")
            return True
        except Exception:
            # TODO: This could also be permission-related, not just non-existence.
            # We should handle this more gracefully in the future.
            # For now, we assume the branch does not exist if an exception is raised.
            return False

    def get_mergebot_yml(self):
        """
        Retrieves and parses the contents of the .mergebot.yml configuration file from the repository.

        This method attempts to:
        - Fetch the .mergebot.yml file from the default branch.
        - Decode its base64-encoded contents.
        - Parse the YAML content and return it as a Python object.

        Returns:
            The parsed YAML content as a Python object, or None if the file does not exist or cannot be read.

        Raises:
            InvalidMergebotYAML: If the .mergebot.yml file exists but contains invalid YAML.
        """
        try:
            file = self.get_file_contents()
            content = base64.b64decode(file.content).decode("utf-8")
            return yaml.safe_load(content)
        except yaml.YAMLError as e:
            raise InvalidMergebotYAML(f"Invalid YAML in .mergebot.yml: {e}")
        except Exception:
            return None

    @abstractmethod
    def onboarding_pr_exists(self):
        """
        Checks if an onboarding PR from branch_name to the default branch already exists.
        Returns the PR link if found, else None.
        """
        raise NotImplementedError("This method should be implemented by subclasses.")

    @abstractmethod
    def create_onboarding_pr(self, default_content: str):
        """
        Creates an onboarding PR to add .mergebot.yml to the default branch.
        Returns the PR link.
        """
        raise NotImplementedError("This method should be implemented by subclasses.")
