# config.yaml

llm:
  model: "azure/gpt-4.1"

repository:
  type: "gitlab"

  gitlab:
    url: "https://gitlab.its.getingecloud.net"
    project: "dts/anthea/iac-layers/aks-iac"
    base_branch: "master"

crews:
  CodeAnalysis:
    llm:
      model: "azure/o3-mini"
  ImpactEvaluator:
    llm:
      model: "azure/o3-mini"
  TestAnalysis:
    llm:
      model: "azure/gpt-4.1"
